# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Push directory to another repository
      uses: cpina/github-action-push-to-another-repository@v1.7.2
      with:
        commit-message: ${{ github.event.head_commit.message }}
        target-branch: dev

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
